"""remove avatar_url from users

Revision ID: dae256e9ab38
Revises: d8a65a9dcf84
Create Date: 2026-03-22 12:08:48.756701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae256e9ab38'
down_revision = 'd8a65a9dcf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
